image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - ~/.cache/pip

before_script:
  - python -V  # Print out python version for debugging

linter:
  stage: build
  allow_failure: true
  script:
    - pip install flake8 black
    - cd spring-webmvc-python
    - make style

test:
  stage: test
  script:
    - pip install pytest pytest-cov pytest-custom_exit_code
    - cd spring-webmvc-python
    - pip install -e .
    - python -m pytest

