#### build

#### deploy

####  start at local for debug

start-spring-webmvc-local:
	@:

### setup environment for local

init-python:
	pip3 install pipenv
	pipenv install --dev
	pipenv run flake8 --version
	pipenv run pytest --version
        
install:
	pipenv install --dev

shell:
	pipenv shell
